### ISSUE TITLE
Link in readme point to the wrong david-dm

### ISSUE THREAD

**Issue by tomap** [hexojs/hexo-asset-pipeline#9]
In the readme, https://github.com/hexojs/hexo-asset-pipeline/blob/master/README.md
The link to David js should point to 
https://david-dm.org/hexojs/hexo-asset-pipeline

**Comment by bhaskarmelkani** [comment]
Hey,

Can you create a PR for it ?

**Comment by tomap** [comment]
Done :)

**Comment by bhaskarmelkani** [comment]
Thanks a lot for your help :)
